### ISSUE TITLE
Selecting hardware API for output

### ISSUE THREAD

**Issue by fred-dev** [npisanti/ofxPDSP#11]
Hi, I really love this addon, I am having a lot of fun with it and have used it for a great project. I have a one request, on windows I need to be able to select the API to get my output working (I think this is because I have asio4All. It would be convenient to somehow expose the API setting that soundstream has from your `engine.listDevices()` and `engine.setDeviceId()` functions, I am guessing this is also useful on linux.

**Comment by npisanti** [comment]
well, that was a good idea, i just added the `setApi()` method to `pdsp::Engine`, and i also added it in the `example_basics1_patching`. Can you git pull ofxPDSP now and let me know if it works on your machine?

**Comment by fred-dev** [comment]
Wow, super fast, I away from the machine on question, seems to work on my other machine though. I'll do another check as well when I get back I town.
