### ISSUE TITLE
destruct or discconect

### ISSUE THREAD

**Issue by fred-dev** [npisanti/ofxPDSP#14]
I have a strange issue, I am using a file player, (a copy of your file player example - (https://github.com/npisanti/ofxPDSP/blob/master/example_song_player/src/AudioPlayer.h) and granular synthesis on raspberry pi.

When I load a straight file to play before loading my granular stuff everything is ok. If I load the granualr stuff afterward it says it loads ok, but fails, no audio comes from the granular stuff even though no errors are reported.

As I wanted to do this dynamically I wanted to know if there is a way to delete objects and connections properly. I tried adding a destructer to the grain cloud class and in the audiofile player class but it does not help.

Is there a proper way to connect and disconnect to the engine and delete objects?

Like

`	narrCloud.out_L() >> narrAmpControl[0] * dB(12.0f) >> engine.audio_out(0);
`
But the opposite?

**Comment by npisanti** [comment]
All the inputs and outputs should automatically disconnect on destruction. Also, you are not having any segfaults, so everything should be ok, but something is not playing. 
When you load the granular "stuff" the audio player still works or everything stop playing?
Could you please precisely write down the steps that cause the malfunction or even write a really simple test app to replicate this problem? 

PS: there are function to disconnect ins/outs in realtime, you can use `yourPatchable.out("tag").disconnectOut()`, `yourPatchable.out("tag").disconnectOut()`,  or `yourPatchable.disconnectAll()` to disconnect all the input/outputs, for example `narrCloud.out_L().disconnectOut()` or `narrAmpControl[0].disconnectAll()`.

**Comment by npisanti** [comment]
could not replicate, closing
