### ISSUE TITLE
Grain cloud behavior

### ISSUE THREAD

**Issue by fred-dev** [npisanti/ofxPDSP#16]
In the grain cloud, I notice that when I disengage the granular, by lifting off the mouse, the last position is still active. This makes sense for moving through the position in a linear fashion, however (I am using the grain cloud example as a reference here), when I click on a position in the file and then release the mouse I would expect when I click the mouse again and engage the controlOn(x,y) method that the grains from the previous position do not play, but currently they do play until they are all cleared.

Is there a way to change this behavior, I guess a way to clear all the samples from the buffer from the last position and only play samples from the current position, the way it reacts when you engage the grains for the first time?

**Comment by npisanti** [comment]
it happens as pdsp stop computing as soon as you lift the mouse, when you click again it continue the last computations. It is the intended for pdsp to work this way to spare cpu cycles. 

GrainCloud is a really high level module, the behavior you want could be gained by making your own version of the GrainCloud, that would be something for a pretty advanced pdsp user.
