### ISSUE TITLE
not an issue... looking for a good example to make a step sequencer...

### ISSUE THREAD

**Issue by moebiussurfing** [npisanti/ofxPDSP#19]
hey I am trying to replace a timer based step sequencer like https://github.com/genekogan/ofxSequencer, because of the unstable and drifting clocking.

![Screen Shot 2019-05-05 at 15 21 01](https://user-images.githubusercontent.com/2106149/57194731-7dc77f00-6f4a-11e9-86fa-bb74c63baf7d.png)

This addon have a clicking system to fill the square steps (bool/int/float ofParameters), but it's a little tricky and maybe I'll like to use ofxGuiExtended from scratch for that.

So I thought to use the PDSP engine just to replace the timer clock for the one from audio buffer engine:
( https://forum.openframeworks.cc/t/accurate-sequencing/3404/16 )
( https://forum.openframeworks.cc/t/music-sequencer-bpm-slightly-off/25067/2 )

So I would like to know what's a good point to do this from your examples. 
I build all the scoring/sequencer examples. I have seen maybe this one as a good 'template': example_sequencing5_passing_data
There are also this ones from your np-patches (but they are not compiling now..): 
Euclidean : euclidean rhythm generator
Tracker : file based tracker with probability for each step

Any suggestions are appreciated. Cheers

**Comment by moebiussurfing** [comment]
I have another question about the exclusive use of the audio out port, because in some cases I use ofxPd and sometimes I'll not need to produce audio. 
Should we share the audio ports with ofxPd or OF audio itself? Can we use the buffer from input only?

**Comment by npisanti** [comment]
for the moment everything is triggered by the audio output request so it is always required, even from input, i don't know i will take the time to find to a way to make possible to use just audio input or OSC or midi output. 

The timing of PDSP is accurate to the sample rate as it is calculated based on the sampling frequency and the position in the buffersize, so it is so accurate when used to control PDSP itself but it will be accurate depending on other factor when sending messages out.

Also if you want to use ofxPd, why not code the sequencer in pure data? i think it would be a lot less headscratching than trying to send message from PDSP to puredata (if you don't want to use OSC for that and want to keep everything inside a single oF app)

**Comment by moebiussurfing** [comment]
thanks @npisanti , I understand a little more now.

Then I could use only the clock (beat) ticks, not much complex... I can store the grid steps in OF.
I will not always use PD, because my sequencer will be used mainly to move trigs/animations/3d objects, (not audio in most cases). 

Not sure if it worth to use ofxPd just for the timer/ticker... but it's a way. ofxPDSP seems 'more internal' and 'light weight' than ofxPd, maybe i am wrong... 

So, do you think your 'example_sequencing5_passing_data' is good template to check? (No problem if uses the audio port) It seems we can change the step patterns inside the ofxPDSP engine and read from them... 
Sorry for still asking, but sometimes a wrong ways loses more time. ;)

**Comment by npisanti** [comment]
if your sequencer is more for visual, my advice is don't use ofxPDSP as it will add soo much code to recompile to your project that you don't need. Reimplementing the clock to be tighter would be a much better choice, it won't lock the audio and it would have much less dependeciens, making recompiling your code faster.

just check out `std::chrono::high_resolution_clock`, if you're on any *nix system it would be the best, some years ago in windows it wasn't that "high resolution" 
https://en.cppreference.com/w/cpp/chrono/high_resolution_clock

anyway the eyes are much less accurate than the ears in detecting jitter so it would be fine

**Comment by npisanti** [comment]
PS: another option for you would be to find a working repo of ofxTimeline, there are so much different version of that i can't count them

**Comment by moebiussurfing** [comment]
Cool, I'll see. I tried ofxTimeline sometime ago, but with all the gui only. Thanks. (PS: Recently I discovered that you can search in GitHub 'oxTimeline fork:true' and then to sort for recent updated forks. Very helpful)

**Comment by npisanti** [comment]
oh, cool trick, good to know!

**Comment by moebiussurfing** [comment]
yes, it's really annoying the default github search behaviour because when looks into forks of a repo, they appears as alphabetic order.

Again related to my timing thing, and just in case you didn't looked ofxMidi recently... there's new midi clocking and timing sync functions:
https://github.com/danomatika/ofxMidi/tree/master/midiTimingExample

I used that to use external midi clock to my tiny step sequencer and it works fine.

**Comment by npisanti** [comment]
mmm i should think about adding midi clock to ofxPDSP, thanks
