### ISSUE TITLE
Few example not compiling on linux with Qtcreator.

### ISSUE THREAD

**Issue by rdtor** [npisanti/ofxPDSP#21]
I tried some example and they are working fine, I was really excited about the wolfram example but it is not compiling, i even tried the one present in nb-patches they too fail.
Here is one example of error trying to run example_midi_polysynth

/home/s***/Programs/openframeworks/openframeworks-nightly/of_v20190324_linux64gcc6_release/addons/ofxPDSP/example_midi_polysynth/src/ofApp.cpp:27: error: undefined reference to 'PolySynth::setup(int)'
/home/s***/Programs/openframeworks/openframeworks-nightly/of_v20190324_linux64gcc6_release/addons/ofxPDSP/example_midi_polysynth/src/ofApp.cpp:107: error: undefined reference to 'PolySynth::Voice::meter_pitch() const'
/home/s***/Programs/openframeworks/openframeworks-nightly/of_v20190324_linux64gcc6_release/addons/ofxPDSP/example_midi_polysynth/src/ofApp.cpp:114: error: undefined reference to 'PolySynth::Voice::meter_mod_env() const'
collect2: error: ld returned 1 exit status

**Comment by npisanti** [comment]
actually i'm on linux all the time, so can you point me the version of qtcreator you are using so i can try to reproduce this? 

PS: are you able to compile those with `make` ?

**Comment by rdtor** [comment]
Qt Creator 4.9.0
Based on Qt 5.12.3 (GCC 8.3.0, 64 bit), all example do compile when using make

**Comment by npisanti** [comment]
you are creating the projects using the project generator included in oF 0.10.1 linux release ?

**Comment by npisanti** [comment]
in the oF page there is written that oF has been tested only with qtcreator 4.6 and 4.6.1, i don't know if the information is up to date, do you have problem just with ofxPDSP or even with other addons or included examples? in that case could be a problem in the project generator

https://openframeworks.cc/setup/qtcreator/

**Comment by rdtor** [comment]
With Qt creator i am having issue even working some of box2d addon example, on 0.10.1, so far i am getting used to makefile and vim to work with openframeworks project, feel free to close the issue. Thx

**Comment by npisanti** [comment]
oook, i will close it as it is an oF related problem not specific to ofxPDSP. 

If it could help and you want to try something different as IDE i also made some scripts to automatically geneare visual studio code projects:

https://github.com/npisanti/of_vscode
