### ISSUE TITLE
error in example_wavesynth_pc_keys

### ISSUE THREAD

**Issue by loicgithub** [npisanti/ofxPDSP#23]
Hello,
there is an error in error in example_wavesynth_pc_keys, it only outs one channel. 
I found the error, it's in synth.cpp

it's because of this line:
chorus.ch(1) >> gain.ch(0);

it must be:
chorus.ch(1) >> gain.ch(1);

I also noticed that the midin selection of port does not implement the port selection by name as in ofxmidi.
For selection of audio device, I also had some issues. It works perfect for my external soundcard but with my (old 2009 beginning) iMac it apparently doesn't for the internal audio device. I can't if it's specific for this model or to all macintosh's computers.

Best Regards,
Loïc

**Comment by npisanti** [comment]
mmm i can correct the typo in the wavesynth example, it's an error i made when i switched to the `.ch()` methods. 

i'll put the selection of the port by name in my //TODO, internally ofxPDSP uses ofxMidi.

I tested pdsp on a mac mini internal speaker and it works, does the standard oF `examples/sound/audioOutputExample` work?

**Comment by npisanti** [comment]
just added the methods for selecting the midi input by name, you can `git pull` and try them out if you want =)

**Comment by loicgithub** [comment]
yes, standard oF examples/sound/audioOutputExample works with both the
internal audio device and my external firewire device. I did not try to
switch from one device to the other in the code itself, I just used the
code without any changes and use the mac os system preferences to select a
different default device.

The example_basics1_patching wich use output only of pdsp works actually
with both the external device and the internal device, except that
controlling the output volume with the the mac os control doesn't works. I
tried the examples with input and output and input only and I think the
input doesn't work, and apparently input and output are seen as different
devices.

here is what I get from the xcode console:

*2019-06-11 16:37:00.717 example_audio_inputDebug[1735:79599] Cannot find
function pointer NewPlugIn for factory C5A4CE5B-0BB8-11D8-9D75-0003939615B6
in CFBundle/CFPlugIn 0x10142ce30
</Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin> (bundle, not loaded)*

*[notice ] ofSoundStreamListDevices: *

*[Unkown API: 0] Apple Inc.: Built-in Microphone [in:2 out:0] (default in)*

*[Unkown API: 1] Apple Inc.: Built-in Input [in:2 out:0]*

*[Unkown API: 2] Apple Inc.: Built-in Output [in:0 out:2]*

*[Unkown API: 3] Digidesign: Digi CoreAudio Device [in:0 out:0]*

*[Unkown API: 4] M-Audio: FireWire 410 Multichannel [in:4 out:10] (default
out)*


*[notice ] [pdsp] engine: starting with parameters: buffer size = 512 |
sample rate = 44100 | 2 inputs | 2 outputs*


*[ error ] RtApiCore::probeDeviceOpen: the device (0) does not support the
requested channel count.*

*[notice ] [pdsp] engine: started | buffer size = 512 | sample rate = 44100
| 2 inputs | 2 outputs*


Le mar. 11 juin 2019 à 14:21, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
ah yes, in this case you should use two different methods to set the input and the output devices IDs, otherwise it won't work, please try something like:
```cpp
    engine.setInputDeviceID(0); // built in microphone
    //engine.setInputDeviceID(1); // built in input
    engine.setOutputDeviceID(2);
    engine.setup( 44100, 512, 3); 
```

**Comment by loicgithub** [comment]
yes, this works, thanks. It seems that the only way it works, i.e., setting
an input AND an output even if you don't need it.
I used the example_analysis for testing. I didn't see in the code anything
about using outputs so it should not be a problem.
Setting only the input doesn't (not using engine.setOutputDeviceID(2); )  ,
in this case I get:
*[ error ] RtApiCore::probeDeviceOpen: the device (0) does not support the
requested channel count.*

It seems that it tries to set the device 0 as output.
Even if I do not set channels for outputs ( I mean: engine.setChannels(2, 0);
)
I don't get the error about channel count anymore but it's not working
anymay.

I tried to change the 3rd to 1 (number of buffers in the audioQueue) set to
3 in the code argument of engine.setup( 44100, 512, 3);
but it doesn't change anything.

Le mar. 11 juin 2019 à 21:31, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
yes, for the way ofxPDSP works it assumes there is always an output running, audio input was meant more for audio input processing than audio analysys (there are other very good addons for audio analysis for oF). Making it run just by using an input without an output is not a priority at the moment. 

The number of audio buffer in the queue should be at least 2 ( i think most audio API will just use 2 if you put one, one buffer elaborating at the moment and the other playing by the speaker, adding more buffer adds a delay but let you avoid clicks, clicks happens when  the playing device finished to play its actual buffer and another buffer isn't ready to play )

**Comment by loicgithub** [comment]
Thank you for your answers, maybe that should be a good idea to put
somewhere in the doc or in the examples or both the fact that you MUST set
a valid output device to use input, just the way you explained it to me :)

Le mer. 12 juin 2019 à 10:50, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by loicgithub** [comment]
I tested Midiin openport using name and it works good, both using real (usb keyboard) and virtual port with IAC Bus or from another software virtual output.

**Comment by npisanti** [comment]
yes, i'll put in some lines in all the audio input examples to explain that =)

the docs are generated by doxygen, but i don't think they are really that handful to read, maybe i should make a wiki or guide like in the ofBook with various sections explaining the general working of pdsp

( it's always hard to make docs, as when API changes everything has to be rewritten )
