### ISSUE TITLE
ToGateTrigger to float number

### ISSUE THREAD

**Issue by d3cod3** [npisanti/ofxPDSP#24]
Hi, i'm trying to get a trigger from an audio signal and reading the trigger as 0/1 float number.

This is what i have:

```c
pdsp::FullWavePeakDetector  peakDetector;
pdsp::EnvelopeFollower      follower;
pdsp::ToGateTrigger         toTrigger;
pdsp::ValueControl          thresh_ctrl;

// then in setup()

thresh_ctrl >> toTrigger.in_threshold();
thresh_ctrl.set(0.5f);
thresh_ctrl.enableSmoothing(10.0f);

audioIN >> peakDetector >> follower >> toTrigger;

// then in update

printf("Trigger: %f", toTrigger.meter_gate());
```

But is not working (always zero). Can you tell me what i'm doing wrong?
Maybe the patch is not correct?

Thank you in advance!

**Comment by npisanti** [comment]
if you don't patch `toTrigger` to anything it is never processed, as DSP in pdsp have lazy processing to spare cpu cycles, you should patch it at least to a `pdsp::Engine` blackhole:
```cpp
toTrigger >> engine.blackhole();
```

**Comment by d3cod3** [comment]
Fantastic!
Thank you

**Comment by npisanti** [comment]
you're welcome!
