### ISSUE TITLE
No Audio input ?

### ISSUE THREAD

**Issue by AnasGhrab** [npisanti/ofxPDSP#26]
I'm trying the example_analysis on os X (10.12.6) and the build-in input. Everything seem to be ok on the console, but I do not see anything on the scope :

```
[notice ] ofSoundStreamListDevices: 
[Unkown API: 0] Apple Inc.: Built-in Input [in:2 out:0] (default in)
[Unkown API: 1] Apple Inc.: Built-in Output [in:0 out:2] (default out)

[notice ] [pdsp] engine: starting with parameters: buffer size = 512 | sample rate = 44100 | 1 inputs | 0 outputs

[notice ] [pdsp] engine: started | buffer size = 512 | sample rate = 44100 | 1 inputs | 0 outputs

```

Here is the content of the setup() : 

```
    engine.listDevices();
    engine.setDeviceID(0);
    //engine.setInputDeviceID(0);
    engine.setChannels(2, 0);
    
    // patching the scope
    engine.audio_in(0) >> scope >> engine.blackhole();
```

**Comment by npisanti** [comment]
it should be:
```cpp
   engine.setChannels(2, 2);
    // patching the scope
    engine.audio_in(0) >> scope >> engine.blackhole();

    engine.listDevices();
    engine.setInputDeviceID(0);
    engine.setOutputDeviceID(1);
```
as stated in a comment in both the examples that use audio input. At the moment, output channels are required to use the audio input. The audio input of ofxPDSP is mainy intended for processing audio signal, can be also used for analysis but it is not its main purpose, so an output is required.

PS: it's better to set up and start the engine after all the patching.
