### ISSUE TITLE
MidiKeys maxNotes is sometimes non-zero

### ISSUE THREAD

**Issue by nspotrepka** [npisanti/ofxPDSP#29]
In MidiKeys.cpp, line 75

`for(int i=0; i<this->maxNotes; ++i){
                gates[i].unLink();
                values[i].unLink();
}`

The problem is

`this->maxNotes` is never initialized to zero
so `gates[i].unLink();` throws a `EXC_BAD_ACCESS` occasionally

**Comment by npisanti** [comment]
ah yes, they're in the wrong order, it's initialized in line 80

fixing this now, thank you very much for catching it!

**Comment by nspotrepka** [comment]
Ah! `setPolyMode` was fine before. What is needed is `maxNotes = 0;` in the constructor because the error was that `maxNotes` was some garbage value, not zero.

**Comment by npisanti** [comment]
ah ok, it shouln't give `EXC_BAD_ACCESS` with the changes, but setting `maxNotes=0` in the costructor should be done anyway, doing it now

**Comment by npisanti** [comment]
ah sorry, i just saw that setPolyMode(8, 1) is called in the constructor, so initializing the notes to 0 the correct way with the new `setPolyMode()`

can you test it ?

**Comment by nspotrepka** [comment]
The reason `this->maxNotes = maxNotes;` is called after is so that `gates` and `values` are `unLink`ed with the old `this->maxNotes` value.

So you are correct. Your changes should prevent `EXC_BAD_ACCESS` ... but will also leave some `gates` and `values` linked, which I don't know if this poses an issue or not, but it could lead to unintended behavior.

**Comment by npisanti** [comment]
ah yes, so this could be better, as it should link everything anyway in the successive lines
```cpp
void pdsp::midi::Keys::setPolyMode(int maxNotes, int unisonVoices ){
      
        this->maxNotes = maxNotes;

        for( auto & gate : gates ){
                gate.unLink();
        }
        
        for( auto & value : values ){
                value.unLink();
        }
        // ...
```

**Comment by npisanti** [comment]
i pushed the changes, let me know if something is still wrong

**Comment by nspotrepka** [comment]
Looks awesome! Would be great to see the same in `setMonoMode`.

**Comment by npisanti** [comment]
done!
