### ISSUE TITLE
example-midi_polysynth crashes when releasing a key while more than 4 keys are hold

### ISSUE THREAD

**Issue by ukelady** [npisanti/ofxPDSP#3]
steps to reproduce:
1. press and hold more than 5 keys at the same time
2. release one key

the app crashes at the function: ofxMidiKeysBuffers::processPolyMidiNoteOn

it crashes at the line:
notes[i].note == noteNumber

when accessing notes[4], while there are only 4 notes

Also, sometimes there are stuck notes with very light volumes...

**Comment by npisanti** [comment]
i tried to replicate this bug on Debian(64bit) and OSX10.10.5 with XCode 6.4 without success, what are your platform and IDE versions?

**Comment by ukelady** [comment]
I am using OS 10.11.2 with XCode 7.1 :)

**Comment by npisanti** [comment]
i still have to get XCode 7, maybe it's time. In the meanwhile i've made a minor fix to ofxMidiKeyBuffers removing a variable that could have caused this bug, please fetch the repo and let me know if it works now

**Comment by ukelady** [comment]
Hi,

I tried the latest version. There is no sound when I triggered some midi
notes.

I set a break point here:

ofxMidiInProcessor::newMidiMessage
When I triggered a midi note it did land on this function (twice, for
note-on and off I assume), so I guess my midi controller is correctly
connected to the app...

**Comment by npisanti** [comment]
what midi controller are you using? i tested it with a midi-keyboard like controller (korg micro key 25), on OSX 10.10.5, XCode 7.1 and it still works fine

**Comment by ukelady** [comment]
I use M-Audio keystation mini32

I can test with another two midi controllers later!

**Comment by ukelady** [comment]
I tried another midi controller and the polyphony works fine. no more crash
:) thanks

**Comment by npisanti** [comment]
perfect, i'm closing the issue!
