### ISSUE TITLE
pdsp::PatchNode error on creating var [WINDOWS]

### ISSUE THREAD

**Issue by d3cod3** [npisanti/ofxPDSP#33]
Hi,
i'm having a weird crash trying to create some pdsp::PatchNode variable at startup; i'm using those variables as temporary links to audio streaming inputs/outputs, so i can connect/disconnect whatever.

So this is happening only on Windows, the exact same code is perfectly working on osx/linux!

I have somewhere in the setup:

pdsp::PatchNode tempPN;
this->pdspOut[i] = tempPN;

So just creating PatchNode vars and storing it in a vector, just that is causing the crash!

Even:

pdsp::PatchNode tempPN;
//this->pdspOut[i] = tempPN;

is crashing, so basically the culpable line is the **pdsp::PatchNode tempPN;** ????

Probably it must be related with something low level that i'm not aware of, so if you can shine a light for me, it would be really appreciated!!

Thanks in advance!

**Comment by npisanti** [comment]
it is strange that pdsp gave you no warning, you are copyng a `pdsp::PatchNode`, that should spit out some warnings about not copying them, and it will generate an assert on debug mode

if you want to create a `pdsp::PatchNode` at runtime you should create it with `new pdsp::PatchNode` and assign the pointer to a vector 

i want to explitily avoid copying or moving around pdsp modules as no clear behavior can be given for that operation when they are already patched to something.

anyway the fact that creating a pdsp object in the setup crash something is strange (but it could happen as i never tested that, pdsp modules are not meant to be created just for the lifetime of a function )

Can you make me the most minimal ofApp to test this?

**Comment by d3cod3** [comment]
Well, now it's pretty clear!

I've just changed the init to a pointer

pdsp::PatchNode *tempPN = new pdsp::PatchNode();

and it's working like a charm!

The weird issue was that same code, crashing only on Windows, while perfectly running on OSX and Linux, but anyway, problem solved!

Thanks for your help!

**Comment by npisanti** [comment]
i will take some time when i can to make more windows testing, i have to do it as at the moment ofxPDSP doens't pass the appveyor CI, so i will also check this issue.

Thanks for reporting!
