### ISSUE TITLE
problems with dynamic allocation

### ISSUE THREAD

**Issue by unexCoder** [npisanti/ofxPDSP#34]
Hello. I was developing and having a lot of fun with the lib the last two months and i had composed a full six tracks album. Each track is launched once with a hardcoded number. But now i would like to get better the app by adding some user interface to be able to choose between tracks and i am having some problems (i thinck with Sequence objects).
Here the log. Thank you very much!

[pdsp] score section output already used as value out, assignation invalid
Assertion failed: (false), function pdsp_trace, file ../../../../../../addons/ofxPDSP/src/sequencer/../DSP/pdspFunctions.h, line 31.
Message from debugger: The LLDB RPC server has crashed. The crash log is located in ~/Library/Logs/DiagnosticReports and has a prefix 'lldb-rpc-server'. Please file a bug and attach the most recent crash log.

**Comment by npisanti** [comment]
you cannot use a `pdsp::ScoreSection` output both as trigger out and as value out, you have to choose one of the two modes, `pdsp_trace` is just a debug help for tracing back the line of code where you did the invalid operation.

The easiest way would be just to use totally different scoresections for each track, and stop the scoresections of non-playing tracks when is necessary.

**Comment by unexCoder** [comment]
thank you!

**Comment by unexCoder** [comment]
thank you!

**Comment by unexCoder** [comment]
thank you!
