### ISSUE TITLE
Testing OSC 

### ISSUE THREAD

**Issue by macramole** [npisanti/ofxPDSP#35]
Hi, we are implementing ofxPDSP in our application AudioStellar (http://audiostellar.xyz/)

We are having difficulties understanding how to test if an OSC message is arriving to our application.

We are using pdsp::osc::Input Class

We need to make a custom behavior when an OSC message arrive, so we think we should be using **parser (string oscAddress, int argument=0)**

Documentation says: get a reference to the parser for the selected address and argument. You can assign a lambda function to this value to elaborate the signal

Can you provide an example on how to do this?, we are not into lambda functions and we tried googling but still can't understand the syntax.

Thanks in advance.

**Comment by npisanti** [comment]
ah sorry, i was using that experimentally and i still have to do a proper documentation, there are some examples inside this code, into the `oscMapping` function from line 175

https://github.com/npisanti/motore_entropico/blob/master/ensemble/src/ofApp.cpp

the parser is used to do some operations on the values of the incoming message, so it only works on a specific argument on the message, it is something like this:

```cpp
osc.parser("/address", argumentindex) = [yourcaptures]( float value ) noexcept {
    // do some operations here 
    // ...
    // ...
    return modifiedvalue; 
    // return return pdsp::osc::Ignore;
};
```
returning `pdsp::osc::Ignore` will make the patched osc output ignore the event. This lambda is executed inside the audio thread, so as usual don't put anything too expensive to computate there and beware of thread-safety 

in your case you want to do something like this
```cpp
osc.parser("/address", index) = [index]( float value ) noexcept {
    std::cout<< "message arrived at /address, argument="<<index<<"\n";
    return return pdsp::osc::Ignore;
};
```
however this code is just for testing, NEVER use `std::cout` into an audio thread ( as all the things explained here http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing )

**Comment by macramole** [comment]
Nicola, thanks for writing back. That syntax look crazy will definitely try it out next week.

In case we need to do something a little more expensive, would you suggest to use ofxOSC directly ?

Thanks for this lib, it is working very nicely with our software, we are very excited to use it

**Comment by npisanti** [comment]
it depends, ofxPDSP under the hood uses a modified version of the ofxOscReceiver, to make the timing very tight. If you need OSC just for controlling parameters and not for triggering synths then timing is not your problem and you can use ofxOsc, otherwise you will get loose timing and you need to use the parser.

PS: yes lambda function can be complicated, but make the syntax less verbose and if you need to use ofxPDSP they are also used for the sequencer so you need to check them out : https://openframeworks.cc/ofBook/chapters/c++11.html#lambdafunctions
