### ISSUE TITLE
Is it possible to plug output to a WAV file ?

### ISSUE THREAD

**Issue by macramole** [npisanti/ofxPDSP#36]
I don't know it this has sense or not, but we were thinking it would be cool to record a performance. We haven't found a *file module* , do you think that is possible ?

Thanks

**Comment by npisanti** [comment]
Not at the moment, that would require some live sampling module. 

But you can route ofxPDSP into a DAW or other software for recording. If you are on linux you can even just do it on the command line with `jack_capture`.

**Comment by macramole** [comment]
Yes, that's how we are doing it at the moment. Using SoundFlower in Mac also works fine.

Thanks.

**Comment by npisanti** [comment]
You're welcome =)
