### ISSUE TITLE
Move constructors

### ISSUE THREAD

**Issue by nspotrepka** [npisanti/ofxPDSP#38]
I've run into some cases where I need to implement a move constructor, namely, when there is a vector to be resized. Here are some examples:

<pre>
pdsp::PatchNode::PatchNode(PatchNode && other) noexcept
: output(other.output) {
    other.output.buffer = nullptr;
    other.output.state = Unchanged;
    addInput("patch", input);
    addOutput("patch", output);
    updateOutputNodes();
    input.setDefaultValue(0.0f);
}
</pre>

<pre>
pdsp::ExternalInput::ExternalInput(ExternalInput && other) noexcept
: buffer(other.buffer), output(other.output), inputUpdated(other.inputUpdated) {
    other.buffer = nullptr;
    other.output.buffer = nullptr;
    other.output.state = Unchanged;
    other.inputUpdated = false;
    addOutput("signal", output);
    updateOutputNodes();

    if (dynamicConstruction) {
        prepareToPlay(globalBufferSize, globalSampleRate);
    }
}
</pre>

@npisanti Can I get your opinion on if I'm doing this correctly, and if everything looks good, should I go ahead and submit a pull request, or multiple pull requests?

**Comment by npisanti** [comment]
usually when you just make a vector of modules, you use the pattern in the example, where both move and new constructor call the patch() method.

But sincerely, everything in oF it's already dynamically allocated on the heap ( the whole ofApp is in the heap ), so in the next release i was about to thinking about just use smart pointers for everything, it would make everything more mantainable. 

I absolutely do not want to incourage things getting moved or copied around, that would lead to lot of bugs i'm sure i would have no time to fix.

**Comment by nspotrepka** [comment]
I have not noticed any bugs yet, but I would still need to do more testing. The reason I wrote the `ExternalInput` move constructor was to handle the resizing of `inputs` in `setChannels` inside `pdsp::Engine`, and the reason I wrote the `PatchNode` move constructor was to handle resizing `processor`, which was a modification I made to `pdsp::Engine`, beginning on line 121:
```
    if(this->outputChannels != outputChannels){
        this->outputChannels = outputChannels;
        processor.resize(outputChannels);
    }
```

**Comment by npisanti** [comment]
I'd like to have the possibility of resizing the engine channels while the app is running, but i'm pretty sure that would be implemented better by just using vectors of smart pointers, so no reallocation is ever needed, and nothing is moved around. 

It would just be less code, so less bugs.
