### ISSUE TITLE
Cannot bind to value of unrelated type 

### ISSUE THREAD

**Issue by nightshining** [npisanti/ofxPDSP#4]
Hi there,
I was just running through the tutorial on building modules and I ran into the following error 'Non-const Ivalue reference to type 'pdsp::InputNode' cannot bind to a value of unrelated type 'pdsp::Patchable'.
 
Thanks.

![screen shot 2016-03-28 at 5 52 08 pm](https://cloud.githubusercontent.com/assets/6088743/14091397/113782cc-f50e-11e5-875e-efdd005dcf55.png)

**Comment by npisanti** [comment]
You're using the wrong method, the right method is `addUnitInput(...) `not `addInput(...)`
`addInput()` is used for setting up units (now if I think about it it's a bit confusing, maybe i should change the nomenclature to "addModuleInput(...) for adding input to modules)

**Comment by npisanti** [comment]
please download the last version of ofxPDSP and use` addModuleInput()` instead of `addInput() `(also you have to use` addModuleOutput() `for the third error line)
