### ISSUE TITLE
MidiKeysBuffer keeping highest and lowest note

### ISSUE THREAD

**Issue by nspotrepka** [npisanti/ofxPDSP#40]
@npisanti 

The following code on line 272 of ofx/helper/MidiKeysBuffer.cpp feels arbitrary and is actually problematic for me, since it clashes with how external plugins treat MIDI note stealing.

<pre>
                for(int i=0; i<static_cast<int>(notes.size()); ++i){
                        if(notes[i].note<lowest){
                                lowest = notes[i].note;
                                indexLowest = i;
                        }else if(notes[i].note>highest){
                                highest = notes[i].note;
                                indexHighest = i;
                        }
                }
</pre>

Vote to remove? Would like to hear your thoughts. Having it commented out locally works for me, too.

**Comment by npisanti** [comment]
the highest and lowest notes are the ones that you can ear most in polyphonic composition, so there should be the last notes to be stolen, i made an effort to make it like that. ofxPDSP has some opinion on note stealing and how envelopes should behave and i want to keep it like this.
