### ISSUE TITLE
Having problems building ofxPDSP on windows 10

### ISSUE THREAD

**Issue by skywalkerwin** [npisanti/ofxPDSP#46]
Ive believe I've got the correct dependencies, but I keep getting some linking error (windows 10) in visual studios. Im running the openframeworks v11.0 and the latest versions of ofxPDSP and ofxAudioFile.

Just wanted to see if this looked familiar or if there were any fixes for it.

Problem:
![image](https://user-images.githubusercontent.com/47264358/70404898-ae97f700-19f8-11ea-9b14-de8936c13568.png)

Here are my addons:
![image](https://user-images.githubusercontent.com/47264358/70404923-bd7ea980-19f8-11ea-84c1-364fc7dd72d0.png)

I can build my project if I remove ofxPDSP. It seems like other users are able to get this working on mac, but I am having no luck on my machine.

Any help is appreciated!!
Thanks!

**Comment by npisanti** [comment]
hi!

the class giving the linker error is not something i ever used on ofxPDSP, (nor it is used by included libraries). But i noticed you are still including ofxSIMDFloats, that now is packaged with ofxPDSP and doesn't need to be included as dependency.

Try removing ofxSIMDFloats, clean and rebuild, and let me know. 
Also let me know if you are able to build the included ofxPDSP examples.

**Comment by npisanti** [comment]
Closed as i cannot replicate it.
