### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by wanwannaw** [npisanti/ofxPDSP#6]
hi i've succesfully compiled the examples but they don't seem to work. i got errors like these

RtApiCore::getDeviceInfo: system error (CoreAudio unknown error) getting sample rate info.

RtApiCore::getDeviceInfo: system error (CoreAudio unknown error) getting sample rate info.

[notice ] ofSoundStreamListDevices: 
[0] Apple Inc.: Built-in Microphone [in:2 out:0] (default in)
[1] Apple Inc.: Built-in Output [in:0 out:2] (default out)
[2] globaldelight: BoomDevice [in:2 out:2]
[3] ma++ ingalls for Cycling '74: Soundflower (2ch) [in:2 out:2]
[4] ma++ ingalls for Cycling '74: Soundflower (64ch) [in:64 out:64]
[5] Apple Inc.: After Effects 11.0 [in:0 out:0]
[6] Apple Inc.: Premiere Pro 6.0 [in:0 out:0]

[ error ] RtApiCore::probeDeviceOpen: the device (0) does not support the requested channel count.
[pdsp] engine: started | buffer size = 512 | sample rate = 44100 | 0 inputs | 2 outputs

**Comment by npisanti** [comment]
Inside `ofApp.cpp` you have to set the right index for your output ID, you are opening the microphone input as audio output, from your list the ID 1 ([1] Apple Inc.: Built-in Output [in:0 out:2] (default out))  should be the right one, so edit the code like this:
`
engine.setDeviceID(1); `

Often in the example code you have to check for the right audio/midi device ID and modify it.

**Comment by wanwannaw** [comment]
Thank you! @npisanti This addon is amazing!

**Comment by npisanti** [comment]
thank you for the feedback =)
