### ISSUE TITLE
input example control to right channel error

### ISSUE THREAD

**Issue by loicgithub** [npisanti/ofxPDSP#61]
I notice an error in the audio input example, the code to control time delay is:

  d1_time_ctrl >> delayL.in_time();
    d2_time_ctrl >> delayL.in_time();

it assign both control to the left channel, it should be:
    d1_time_ctrl >> delayL.in_time();
    d2_time_ctrl >> delayR.in_time();

**Comment by npisanti** [comment]
thank you very much for reporting! fixing it now
