### ISSUE TITLE
 error C2039: 'to_string': is not a member of 'std'

### ISSUE THREAD

**Issue by EdwardDeaver** [npisanti/ofxPDSP#63]
Hi, 
I'm trying to compile a new project using ofxPDSP that is an exact copy of 'example_sequencing1". I am using OF 0.11.0 on Windows 10 with Visual Studio 2017.

When I try to compile the program I get the errors:

`1>C:\Users\Edward\Documents\of_v0.11.0_vs2017_release\addons\ofxPDSP\src\sequencer\Function.cpp(74,32): error C2039: 'to_string': is not a member of 'std'

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\random(27): message : see declaration of 'std'

1>C:\Users\Edward\Documents\of_v0.11.0_vs2017_release\addons\ofxPDSP\src\sequencer\Function.cpp(74,41): error C3861: 'to_string': identifier not found

1>C:\Users\Edward\Documents\of_v0.11.0_vs2017_release\addons\ofxPDSP\src\sequencer\Function.cpp(126,32): error C2039: 'to_string': is not a member of 'std'

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\random(27): message : see declaration of 'std'

1>C:\Users\Edward\Documents\of_v0.11.0_vs2017_release\addons\ofxPDSP\src\sequencer\Function.cpp(126,41): error C3861: 'to_string': identifier not found`

Do you know what this error of "'to_string': is not a member of 'std'" is occuring?

**Comment by npisanti** [comment]
this was a recent addition, and i had no way to test it on windows, but it is a really quick thing to fix and i will do it now. Please pull the master branch and try again, then let me know.

thanks for reporting!
