### ISSUE TITLE
can't compile on MAC OSX for Iphone

### ISSUE THREAD

**Issue by t3ke** [npisanti/ofxPDSP#64]
Hello,

Example run without problem on Mac, but when I try different way to run your lib on my Ipad, he definitely have a Apple Mach-O Linker Error.

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'

My specs : macOS 10.12 / Xcode 8 / OF101 / Target ios 10

My project run with ofxMidi, ofxOSc etc.. Every dependency working great, but when i add ofxPDSP via Projet generator, i can't run it.

Any idea ? Is there a software uncompatibility  (Need Xcode 10, updated Framework...) ?

Thanks for your help and thanks for your fantastic work !

**Comment by npisanti** [comment]
this is really strange, can you try to import the included `example_ios` with the project generator?

**Comment by t3ke** [comment]
Problem solve. 

After compare with the example, the problem come from my project > ofxSIMDFloats isn't require for ofxPDSP. 

ofxPDSP and ofxSIMDFloats can't work together.

**Comment by npisanti** [comment]
yes! ofxSIMDFloats is now included in ofxPDSP so it shouldn't be included in the `addons.make` file. Did you find any outdated `addons.make` file somewhere?

**Comment by t3ke** [comment]
No, i would like to add ofxPDSP to an existing project and i have in head that' it require ofxSIMDFloats. Your files are up to date.

**Comment by npisanti** [comment]
ok perfect, so i will close this issue =)
