### ISSUE TITLE
[question] What's the more recent/recommended AudioAnalyzerBand from your repositories?

### ISSUE THREAD

**Issue by moebiussurfing** [npisanti/ofxPDSP#65]
hey @npisanti ,
Thanks for all this amazing work.

I am looking for a simple FFT band analyzer. I looked into your repositories and I see different versions and I want to know which one is these are the more recently updated or recommended:

https://github.com/npisanti/ofxPDSP/tree/master/example_analysis/src
https://github.com/npisanti/np-patches/tree/master/example_analyzer
https://github.com/npisanti/np-analyzer

For the moment I do not need other ofxPDSP features, so maybe I can try other alternatives if you think preferable.

**Comment by npisanti** [comment]
actually those are not FFT, they are splitting the bands with filters and getting the envelope for the different bands, i think the `np-analyzer` repo is the most recent. but for just audio analysis i would prefer ofxGist: 

https://github.com/borg/ofxGist

it has some really nice FFT transients analysis routines. Audio analyzer with ofxPDSP are better for when you want to reduce dependencies.

**Comment by moebiussurfing** [comment]
Thanks, I never used analysis yet. It looks it has other good analysis tools. 

The problem is that ofxOpenALSoundPlayer dependency that do not work on Windows/VS2017. 
It seems that can be replaced with your https://github.com/npisanti/ofxAudioFile, as it's only used to get the buffer to process. Also for live input that could not be required...
I tried to do it but haven't got success. Do you think could be easy that I can do it? (or maybe you have some example if you used ofxGist before...)

I have seen ofxMaxim too that works multiplatform. Also https://github.com/leozimmerman/ofxAudioAnalyzer for Essentia that looks heavier.

**Comment by npisanti** [comment]
that `ofxOpenALSoundPlayer` is needed by the example, but not by the addon, so if you work a bit on patching it to the audio input it will work, i've successfully did it on linux maybe two years ago, but i didn't tested it in the newer versions of oF and probably i don't have the code anymore ( it was just a sketch )

**Comment by moebiussurfing** [comment]
thanks. @npisanti ,
it worked processing live input:
https://forum.openframeworks.cc/uploads/default/original/2X/4/4022673ef48a8c1fd4ae207c5d7e45bacaae26d5.png
