### ISSUE TITLE
Engine::stop() freezes on Windows 10

### ISSUE THREAD

**Issue by macramole** [npisanti/ofxPDSP#66]
Application freezes when calling engine->stop();

I'm compiling using Visual Studio Community 2017. Using ASIO4ALL as the ASIO driver. This doesn't happen on Linux or on Mac.

Since a much more complex example was freezing, I've tried a simple example: example_basics1_patching. I added a line of code for stopping on click and it freezes.

What is actually freezing is the stop() method of ofSoundStream. So I tried the oF example called audioOutputExample which also uses ofSoundStream directly. The stop() method is working fine in that example.

It seems to me that something must be stopped before calling the stop() method but since I don't fully understand ofxPDSP architecture I don't know what could it be, does it ring any bell for you ? maybe stop calling the process function? 

I also tried commenting the lines where patching is done in example_basics1_patching so it just starts the audio server and then stop it, but it also freeze. I was thinking maybe I should unpatch everything before stopping. 

Any ideas ?

Thanks for reading.

**Comment by npisanti** [comment]
can you please also check out the commit `3ebd94e70dbab06b5dc9569d188245c7a4d833f7` and test ? i suspect this could be an issue generated from a recent PR merged

**Comment by macramole** [comment]
good news (I guess), 

I can confirm that checking out that commit makes the bug go away. Now it closes correctly.

**Comment by macramole** [comment]
( oh i forgot, it needs commit 435dd619e79487e855c98a5097fa0a730d15cc7b to work )

**Comment by npisanti** [comment]
due to the current quarantine i'm not able to have access to a Windows pc for fixing / testing this, could you please made a pull request with the needed reverts and changes to make everything work?
