### ISSUE TITLE
Sequencer step time glitch

### ISSUE THREAD

**Issue by d3cod3** [npisanti/ofxPDSP#68]
Hi, i've stepped in some problem with the sequencer, while using it triggering sample files sometimes it seems like the timing was slightly off. so i tested the step time with this code:

```c
// ofApp.h


pdsp::Function                                seq;

std::atomic<int>                              step_millis;

std::chrono::steady_clock::time_point         clock_begin;
std::chrono::steady_clock::duration           time_span;


// ofApp.cpp

//--------------------------------------------------------------
void ofApp::setup(){

  engine.sequencer.setTempo( 108 );

  seq.code = [&]() noexcept {

    time_span = std::chrono::steady_clock::now() - clock_begin;
    clock_begin = std::chrono::steady_clock::now();

    step_millis = static_cast<int>(floor(double(time_span.count()) * 1000 * std::chrono::steady_clock::period::num / std::chrono::steady_clock::period::den));

  }

  // ............

}

//--------------------------------------------------------------
void ofApp::draw(){

  // ............

  ofSetColor(255);
  // printing out the instructions
  string info = "master playhead (bars): ";
  info += to_string( engine.sequencer.meter_playhead() );
  info += "\nStep Time (ms) "+to_string( step_millis );
  info += " \n";
  info += "space : pause/play.\n";
  info += "s : stop.\n";

  ofDrawBitmapString(info, 50, 50 );


  // ............

}

```

![](https://mosaic.d3cod3.org/exports/sequencer_glitch.gif)

As you can see in the animated gif ( slo-mo ), the step time is around 138/139 millis, perfect 
for 108 BPM ( 60000 / 4 / 108 ), but you can see the "glitch" around master playhead at 3.38 ( step 7 of 16 ), 
where the step time goes down to 116 ms, and then come back to the correct 138 ms

It occurs along the time with no regular pattern, at least for what i've observed.

Please tell me if i've done something wrong or i'm not considering some basic issues.
And if not, where can i look to find the reason for that, and maybe fix it?

Thanks a lot for your amazing code!

**Comment by d3cod3** [comment]
https://user-images.githubusercontent.com/141075/86584591-69837580-bf85-11ea-9493-b9bc98797090.gif

**Comment by d3cod3** [comment]
![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)

**Comment by d3cod3** [comment]
https://mosaic.d3cod3.org/exports/sequencer_glitch.gif

Don't know why the gif is not appearing in the comment, maybe because is +2mb

**Comment by npisanti** [comment]
this won't be a good test, as the seq generate messages with a given sample offset, which are then played by `pdsp::SequencerValueOutput` and `pdsp::SequancerGateOutput` 

if you are using pdsp sequencer to control visual there could some jitter, as the sequences are processed at the start of each audio buffer ( but the produced messages are played by the synths with the correct timing given by the produced sample offset value )

**Comment by d3cod3** [comment]
Ok, i'll fix the std::chrono issue, and i understand better now how the sequencer works.

There could be a way to get the correct timed "bang" when the produced messages are playing the synths?

I'll think at some kind of solution, i'll let you know if i end up with something solid

Thanks a lot

**Comment by npisanti** [comment]
sadly i don't think there could be any thread-safe way to do that, but using a smaller audio buffer size will reduce the timing jitter 

the envelope modules have a `meter_triggers()` method to count the number of received triggers, it's thread-safe to check that, when the returned number changes it means a new trigger has been processed, it's in both `pdsp::AHR` and `pdsp::ADSR` 

http://npisanti.com/ofxPDSP/classpdsp_1_1_a_h_r.html#a36d6d0ae5bcc9f5233995663b3ac1c0e

**Comment by d3cod3** [comment]
Ok, thank you so much!

i've found some more info:

using 108 BPM ( 138 millis x step ) a buffer size of 1024 and samplerate at 44100

the jitter occurs with an acceleration of 22 milliseconds ( stepping down the step time at 116 ), always,
with a pause between 7442 and 7558 milliseconds ( more or less )

It happens both on an empty example, without really triggering anything, as on a fully loaded example with synths and samples, and exactly the same numbers on both linux and osx.

Don't know if is useful info in some way

Anyway, i'll take a look at ```pdsp::AHR``` and ```pdsp::ADSR```

Thanks again!
