### ISSUE TITLE
Implementing a kick synth

### ISSUE THREAD

**Issue by d3cod3** [npisanti/ofxPDSP#69]
Hi, i'm trying to implement a basic kick synth, i'm following this:

![Sin título](https://user-images.githubusercontent.com/141075/92246853-a48f2000-eec6-11ea-9ddd-b689e5259650.jpeg)

and this is what i'm using:

```c
pdsp::Amp                     amp;
pdsp::FMOperator        osc;
pdsp::Saturator2           drive;
pdsp::VAFilter                filter;
pdsp::ADSR                   ampEnv;
pdsp::ADSR                   modEnv;

pdsp::ValueControl       osc_freq_ctrl;
pdsp::ValueControl       filter_freq_ctrl;
pdsp::ValueControl       filter_res_ctrl;
```

and

```c
    osc_freq_ctrl >> osc.in_pitch();
    osc_freq_ctrl.set(pdsp::f2p(oscFreq));
    osc_freq_ctrl.enableSmoothing(50.0f);

    filter_freq_ctrl >> filter.in_pitch();
    filter_freq_ctrl.set(pdsp::f2p(filterFreq));
    filter_freq_ctrl.enableSmoothing(50.0f);

    filter_res_ctrl >> filter.in_reso();
    filter_res_ctrl.set(filterRes);
    filter_res_ctrl.enableSmoothing(50.0f);

    pdsp::VAFilter::LowPass12 >> filter.in_mode();

    osc >> amp;
    gate_ctrl.out_trig() >> ampEnv.set(0.0f,240.0f,0.0f,0.0f) >> amp.in_mod();
    gate_ctrl.out_trig() >> modEnv.set(0.0f,15.0f,0.0f,0.0f) * osc_freq_ctrl.get() >> osc.in_pitch();

    amp >> filter >> drive >> engineOutput;
```

Now, the basic concept is working, but the sound is still lacking power/richness, can you give me some clues for a more professional result?

I know it's not a code related issue, sorry for that, but any help will be really appreciated!

If you're interested, i've implemented all this modules from your addon for the [Mosaic](https://github.com/d3cod3/Mosaic) software:

![Sin título2](https://user-images.githubusercontent.com/141075/92247980-4c591d80-eec8-11ea-9fcd-0f42ee835816.jpeg)

and this is a simple patch with some of them ( i'm finishing a refactoring to imgui so they are not all already ported )

![mosaicScreenshot_200904](https://user-images.githubusercontent.com/141075/92248389-e28d4380-eec8-11ea-8e18-bc07e916e1b6.jpg)

Anyway, thanks in advance!

**Comment by npisanti** [comment]
making good kicks it's about your tastes and the style of music and often involves some mixing, compression, EQ etc etc 

you should check out some tutorials about the specific kinds of kick you are wanting to produce

PS: the mosaic interface looks really nice, thanks for sharing!

PPS: this is not an issue or a PDSP bug so i'm closing this thread
