### ISSUE TITLE
Can't build iOS example.

### ISSUE THREAD

**Issue by GoroMatsumoto** [npisanti/ofxPDSP#7]
"FullWavePeakDetector.cpp" and "HalfWavePeakDetector.cpp" are not in ofxPDSP.
Why???
![image](https://cloud.githubusercontent.com/assets/1933467/22150922/12c014f6-df5f-11e6-92a0-785e9686a126.png)

**Comment by npisanti** [comment]
please try updating the iOs project with the oF project generator, those files have now a different name and the old classes are just a typedef, and then let me know

**Comment by GoroMatsumoto** [comment]
It worked. Nice sine tone came here. Thank you.

**Comment by npisanti** [comment]
as i don't have access to an apple computer at the moment, can you please send me a pull request with just the modifications of the iOS project ?

**Comment by GoroMatsumoto** [comment]
I think that you should remove xcode project files.
Other examples don't have those files.
But I could test those example easily via oF project generator app.

How do you think?

**Comment by npisanti** [comment]
could you try downloading ofxPDSP again, removing all the xcode files and then generate the example this way and then let me know if everything worked?

**Comment by GoroMatsumoto** [comment]
OK. I done it.

0. The clean start.
![screen shot 2017-01-24 at 5 56 13](https://cloud.githubusercontent.com/assets/1933467/22223126/11fcaafc-e1fd-11e6-9ddb-98bc517e69eb.png)
1. Loaded the folder.
![screen shot 2017-01-24 at 5 55 59](https://cloud.githubusercontent.com/assets/1933467/22223150/297c854e-e1fd-11e6-876c-5b6a2824ac07.png)
2. Success.
![screen shot 2017-01-24 at 5 56 48](https://cloud.githubusercontent.com/assets/1933467/22223166/3d455cea-e1fd-11e6-98e0-ef995f863f9b.png)
3. Build Succeeded.
![screen shot 2017-01-24 at 6 03 12](https://cloud.githubusercontent.com/assets/1933467/22223227/76966b38-e1fd-11e6-9e39-27cfca20c4d0.png)

I run the example on my iPhone, too.
There are no problems

**Comment by npisanti** [comment]
Thank you! I removed the files so now i can close this issue.
