### ISSUE TITLE
is_playing() returns false when sampler plays in reverse

### ISSUE THREAD

**Issue by juanxa** [npisanti/ofxPDSP#72]
is_playing() does not return true if a sample is being played in reverse.

Playback is reversed like this:

-1.f >> in_direction();
 1.f >> in_start();

Sound plays correctly from the last sample to the first one but is_playing() always returns false.

**Comment by npisanti** [comment]
can you please state to which class the `is_playing()` method belong? `pdsp::Sampler` has no `is_playing()` method. 

Or can you state from which example you are using the `is_playing()` method is? i run a 
```
grep -r "is_playing" .
```
on the whole ofxPDSP codebase and the method you are using is not present.

**Comment by juanxa** [comment]
Please ignore this. I was using a forked version of PDSP. 
Feel free to delete this issue.
