### ISSUE TITLE
`sndfile.hh` file not found error - OF for Android

### ISSUE THREAD

**Issue by narner** [npisanti/ofxPDSP#8]
Hi there, 

Thanks for the great add-on!

I'm trying to create a new OF-Android project with `ofxPDSP`. My setup mirrors that of the OF-Android guide found [here](https://medium.com/@ire_alva/getting-started-with-openframeworks-on-android-5202b92f6582).

After generating the project using OF's Project Generator, and opening it in Android Studio and making the project, I'm getting the following errors:

<img width="1050" alt="screen shot 2017-11-27 at 7 54 49 pm" src="https://user-images.githubusercontent.com/2131591/33297032-df426ab4-d3ac-11e7-9e0b-6dfb16c7584f.png">

I'm using Android Studio 3.0.1. 

Thanks!

**Comment by npisanti** [comment]
i still have to make ofxPDSP work on android too. It was a low priority as the android sound engine has a lot of latency, making it really bad for playing with it in real time. Anyway on linux ofxPDSP uses libsndfile, that should be also available for android, so we should find a way to install libsndfile on android and link it to your program. It will take a while before i can look at it as i'm very busy now, let me know if you find a way (and maybe send me a PR).

**Comment by npisanti** [comment]
i have stopped using libsndfile and libaudiodecoder and started using ofxAudioFile. There is also an example_android now in the repo so i will consider this issue closed.
= )
