### ISSUE TITLE
UI problems on linux 

### ISSUE THREAD

**Issue by figurehe4d** [npisanti/ofxPDSP#9]
Having a bit of an issue getting the any of the example ui to work. any idea what might be causing this? 
![screenshot from 2017-11-30 02-13-04](https://user-images.githubusercontent.com/19341761/33659481-35150332-da35-11e7-801d-a6c66207e88a.png)

**Comment by npisanti** [comment]
what version of Linux are you using? it is a problem that arise only with the examples that uses ofxGui?

**Comment by figurehe4d** [comment]
Fedora 27 
kernel: 4.13.16-302.fc27.x86_64

Looks like the problem was related to ofxGui indeed, /gl/ofBufferObject.cpp needed to have all instances of `GLEW_ARB_direct_state_access`  replaced with `false`.
